import fs from 'node:fs';
import path from 'node:path';
const mk=(id,name,category,engine,tagline,opts={})=>({
  id,name,slug:id,category,engine,
  description:tagline,
  inputLabel:opts.inputLabel||'Input',
  outputLabel:opts.outputLabel||'Result',
  placeholder:opts.placeholder||'Paste your data here…',
  sample:opts.sample||'',
  options:opts.options||[],
  credits:opts.credits??1,
  freeLimit:opts.freeLimit??250000,
  mode:opts.mode||'text',
  seoTitle:`${name} Online — Fast, Private & Free | MicroForge`,
  seoDescription:`${tagline} Runs locally in your browser for privacy. No signup for basic use; API and batch automation available.`,
  h1:name,
  explainer:opts.explainer||`${tagline} Basic processing happens in your browser so your content does not need to be uploaded. Use the shared API and credits when you need automation or higher-volume workflows.`,
  faq:[
    {q:'Is my data uploaded?',a:'For normal browser use, processing runs locally on your device. API requests are processed by the server only when you explicitly use the API.'},
    {q:'Do I need an account?',a:'No account is required for basic browser use. An API key or paid balance is only needed for automation and premium limits.'},
    {q:'Can I automate this?',a:`Yes. The same engine is available through POST /api/tools/${id} using a shared API key and credit balance.`}
  ]
});

export const apps=[
mk('json-formatter','JSON Formatter','JSON','json_format','Beautify JSON with readable indentation.',{sample:'{"name":"Walter","active":true,"items":[1,2,3]}',options:[{id:'indent',label:'Indent',type:'select',values:['2','4','tab'],default:'2'}]}),
mk('json-validator','JSON Validator','JSON','json_validate','Validate JSON syntax and pinpoint parse errors.',{sample:'{"ok": true}'}),
mk('json-minifier','JSON Minifier','JSON','json_minify','Remove unnecessary whitespace from valid JSON.',{sample:'{\n  "name": "MicroForge",\n  "active": true\n}'}),
mk('json-sorter','JSON Key Sorter','JSON','json_sort','Sort JSON object keys recursively for stable diffs.',{sample:'{"z":1,"a":{"d":4,"b":2}}'}),
mk('json-flattener','JSON Flattener','JSON','json_flatten','Flatten nested JSON objects into dot-path keys.',{sample:'{"user":{"name":"Ana","address":{"city":"Buenos Aires"}}}'}),
mk('json-repair','JSON Repair','JSON','json_repair','Repair common JSON mistakes such as trailing commas and single quotes.',{sample:"{'name':'Ana','active':true,}"}),
mk('json-to-csv','JSON to CSV','Data Conversion','json_to_csv','Convert arrays of JSON objects into CSV.',{sample:'[{"name":"Ana","age":30},{"name":"Luis","age":35}]'}),
mk('csv-to-json','CSV to JSON','Data Conversion','csv_to_json','Convert CSV rows into a JSON array of objects.',{sample:'name,age\nAna,30\nLuis,35'}),
mk('csv-cleaner','CSV Cleaner','CSV','csv_clean','Trim cells, remove blank rows and normalize CSV output.',{sample:'name,email\n Ana , ana@example.com \n\nLuis,luis@example.com',options:[{id:'dedupe',label:'Remove duplicate rows',type:'checkbox',default:true}]}),
mk('csv-dedupe','CSV Duplicate Remover','CSV','csv_dedupe','Remove duplicate CSV rows while keeping the first occurrence.',{sample:'name,email\nAna,a@example.com\nAna,a@example.com\nLuis,l@example.com'}),
mk('csv-column-selector','CSV Column Selector','CSV','csv_columns','Keep only selected CSV columns.',{sample:'name,email,city\nAna,a@example.com,Buenos Aires\nLuis,l@example.com,Cordoba',options:[{id:'columns',label:'Columns (comma separated)',type:'text',default:'name,email'}]}),
mk('csv-sorter','CSV Sorter','CSV','csv_sort','Sort CSV rows by a chosen column.',{sample:'name,age\nLuis,35\nAna,30',options:[{id:'column',label:'Column',type:'text',default:'name'}]}),
mk('csv-to-tsv','CSV to TSV','Data Conversion','csv_to_tsv','Convert comma-separated values to tab-separated values.',{sample:'name,age\nAna,30\nLuis,35'}),
mk('tsv-to-csv','TSV to CSV','Data Conversion','tsv_to_csv','Convert tab-separated values to standard CSV.',{sample:'name\tage\nAna\t30\nLuis\t35'}),
mk('csv-to-markdown','CSV to Markdown Table','Data Conversion','csv_to_markdown','Turn CSV data into a Markdown table.',{sample:'name,age\nAna,30\nLuis,35'}),
mk('text-cleaner','Text Cleaner','Text','text_clean','Normalize whitespace and remove invisible clutter from text.',{sample:'  Hello   world!  \n\n\n This   is  text. '}),
mk('remove-duplicate-lines','Remove Duplicate Lines','Text','remove_duplicate_lines','Deduplicate lines while preserving their original order.',{sample:'apple\nbanana\napple\norange\nbanana'}),
mk('remove-empty-lines','Remove Empty Lines','Text','remove_empty_lines','Remove blank lines from pasted text.',{sample:'one\n\ntwo\n   \nthree'}),
mk('text-case-converter','Text Case Converter','Text','case_convert','Convert text to upper, lower, title or sentence case.',{sample:'the QUICK brown FOX',options:[{id:'case',label:'Case',type:'select',values:['upper','lower','title','sentence'],default:'title'}]}),
mk('word-counter','Word Counter','Text','word_count','Count words, characters, lines and estimated reading time.',{sample:'Microapps can solve small problems very quickly.'}),
mk('sort-lines','Sort Lines','Text','sort_lines','Sort lines alphabetically or numerically.',{sample:'zebra\napple\nbanana',options:[{id:'direction',label:'Direction',type:'select',values:['asc','desc'],default:'asc'}]}),
mk('reverse-lines','Reverse Lines','Text','reverse_lines','Reverse the order of lines instantly.',{sample:'first\nsecond\nthird'}),
mk('trim-lines','Trim Lines','Text','trim_lines','Remove leading and trailing whitespace from every line.',{sample:'  first  \n second\nthird   '}),
mk('slug-generator','Slug Generator','SEO','slugify','Create clean URL slugs from titles or phrases.',{sample:'50 Microapps: Fast & Cheap Tools!'}),
mk('keyword-cleaner','Keyword Cleaner','SEO','keyword_clean','Normalize keyword lists, remove duplicates and trim whitespace.',{sample:'json tools, JSON tools, csv cleaner,  micro apps,CSV Cleaner'}),
mk('email-extractor','Email Extractor','Extraction','extract_emails','Extract unique email addresses from text.',{sample:'Contact ana@example.com or sales@example.org. Ana: ana@example.com'}),
mk('url-extractor','URL Extractor','Extraction','extract_urls','Extract unique HTTP and HTTPS URLs from text.',{sample:'Visit https://example.com and https://openai.com/research.'}),
mk('phone-extractor','Phone Extractor','Extraction','extract_phones','Extract likely international and local phone numbers from text.',{sample:'Call +54 11 5555-1234 or (011) 4444 9999.'}),
mk('regex-tester','Regex Tester','Developer','regex_test','Test a regular expression against text and list its matches.',{sample:'Order A-123, B-456, C-789',options:[{id:'pattern',label:'Pattern',type:'text',default:'[A-Z]-\\d+'},{id:'flags',label:'Flags',type:'text',default:'g'}]}),
mk('base64-encoder','Base64 Encoder','Encoding','base64_encode','Encode UTF-8 text as Base64.',{sample:'Hello MicroForge'}),
mk('base64-decoder','Base64 Decoder','Encoding','base64_decode','Decode Base64 back into UTF-8 text.',{sample:'SGVsbG8gTWljcm9Gb3JnZQ=='}),
mk('url-encoder','URL Encoder','Encoding','url_encode','Percent-encode text for safe use in URLs.',{sample:'hello world?x=1&y=2'}),
mk('url-decoder','URL Decoder','Encoding','url_decode','Decode percent-encoded URL text.',{sample:'hello%20world%3Fx%3D1%26y%3D2'}),
mk('html-escape','HTML Escape','Developer','html_escape','Escape HTML special characters safely.',{sample:'<div class="demo">Hello & goodbye</div>'}),
mk('html-unescape','HTML Unescape','Developer','html_unescape','Convert common HTML entities back to characters.',{sample:'&lt;div&gt;Hello &amp; goodbye&lt;/div&gt;'}),
mk('strip-html','Strip HTML Tags','Developer','strip_html','Remove HTML tags and return plain text.',{sample:'<p>Hello <strong>world</strong>.</p><p>Next line.</p>'}),
mk('markdown-to-html','Markdown to HTML','Developer','markdown_to_html','Convert common Markdown syntax into clean HTML.',{sample:'# Title\n\n**Bold** and *italic*\n\n- One\n- Two'}),
mk('meta-tag-builder','Meta Tag Builder','SEO','meta_tags','Generate title, description, canonical and Open Graph meta tags.',{sample:'Fast CSV Cleaner',options:[{id:'description',label:'Description',type:'text',default:'Clean CSV files quickly and privately.'},{id:'url',label:'Canonical URL',type:'text',default:'https://example.com/csv-cleaner'}]}),
mk('robots-txt-generator','Robots.txt Generator','SEO','robots_txt','Generate a basic robots.txt with sitemap reference.',{sample:'https://example.com',inputLabel:'Site URL'}),
mk('sitemap-generator','XML Sitemap Generator','SEO','sitemap_xml','Create a simple XML sitemap from a list of URLs.',{sample:'https://example.com/\nhttps://example.com/json-formatter\nhttps://example.com/csv-cleaner'}),
mk('utm-builder','UTM Builder','Marketing','utm_builder','Add UTM campaign parameters to any URL.',{sample:'https://example.com/landing',options:[{id:'source',label:'utm_source',type:'text',default:'newsletter'},{id:'medium',label:'utm_medium',type:'text',default:'email'},{id:'campaign',label:'utm_campaign',type:'text',default:'launch'}]}),
mk('uuid-generator','UUID Generator','Developer','uuid_generate','Generate RFC 4122 version 4 UUIDs.',{sample:'5',inputLabel:'How many?',options:[]}),
mk('timestamp-converter','Unix Timestamp Converter','Developer','timestamp_convert','Convert Unix timestamps to ISO dates or dates to Unix timestamps.',{sample:'1760000000'}),
mk('sha256-generator','SHA-256 Generator','Developer','sha256','Generate a SHA-256 digest for text.',{sample:'MicroForge'}),
mk('unit-converter','Unit Converter','Calculators','unit_convert','Convert common length, mass and temperature units.',{sample:'10',options:[{id:'from',label:'From',type:'select',values:['m','cm','mm','km','ft','in','kg','g','lb','C','F'],default:'m'},{id:'to',label:'To',type:'select',values:['m','cm','mm','km','ft','in','kg','g','lb','C','F'],default:'ft'}]}),
mk('percentage-calculator','Percentage Calculator','Calculators','percentage','Calculate a percentage of a value.',{sample:'250',options:[{id:'percent',label:'Percent',type:'text',default:'18'}]}),
mk('margin-calculator','Margin Calculator','Business','margin','Calculate gross margin from cost and selling price.',{sample:'100',inputLabel:'Cost',options:[{id:'price',label:'Selling price',type:'text',default:'160'}]}),
mk('markup-calculator','Markup Calculator','Business','markup','Calculate markup percentage from cost and selling price.',{sample:'100',inputLabel:'Cost',options:[{id:'price',label:'Selling price',type:'text',default:'160'}]}),
mk('concrete-calculator','Concrete Volume Calculator','Construction','concrete','Estimate concrete volume from length, width and thickness.',{sample:'10',inputLabel:'Length (m)',options:[{id:'width',label:'Width (m)',type:'text',default:'8'},{id:'thickness',label:'Thickness (cm)',type:'text',default:'12'},{id:'waste',label:'Waste %',type:'text',default:'5'}]}),
mk('brick-calculator','Brick / Block Calculator','Construction','bricks','Estimate wall blocks from wall area and block face dimensions.',{sample:'100',inputLabel:'Wall area (m²)',options:[{id:'blockLength',label:'Block length (cm)',type:'text',default:'50'},{id:'blockHeight',label:'Block height (cm)',type:'text',default:'20'},{id:'waste',label:'Waste %',type:'text',default:'5'}]})
];

let custom=[];try{custom=JSON.parse(fs.readFileSync(path.resolve('data/custom-apps.json'),'utf8'))}catch{};for(const c of custom){if(!apps.some(a=>a.slug===c.slug))apps.push(mk(c.slug,c.name,c.category,c.engine,c.description,c));}
export const bySlug=Object.fromEntries(apps.map(a=>[a.slug,a]));
