import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {apps,bySlug} from './catalog.mjs';import {runEngine} from './engines.mjs';import {createUser,getByApiKey,useCredits,grantCredits,logEvent,getDashboard} from './store.mjs';
const PORT=Number(process.env.PORT||8787);const BASE=process.env.BASE_URL||`http://localhost:${PORT}`;
const publicDir=path.resolve('public');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=(res,status,obj)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(obj))};
const text=(res,status,body,type='text/plain; charset=utf-8')=>{res.writeHead(status,{'content-type':type});res.end(body)};
const body=async req=>{let chunks=[],size=0;for await(const c of req){size+=c.length;if(size>2_500_000)throw Object.assign(new Error('Payload too large'),{status:413});chunks.push(c)}return Buffer.concat(chunks)};
function layout(title,desc,content,canonical='/'){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${BASE}${canonical}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:type" content="website"><meta property="og:url" content="${BASE}${canonical}"><link rel="stylesheet" href="/assets/styles.css"><script type="module" src="/assets/client.js"></script></head><body><header><a class="brand" href="/">MicroForge</a><nav><a href="/tools">Tools</a><a href="/pricing">Pricing</a><a href="/api-docs">API</a><a href="/privacy">Privacy</a></nav></header><main>${content}</main><footer><span>MicroForge — small tools, one shared platform.</span><span><a href="/terms">Terms</a> · <a href="/refunds">Refunds</a> · <a href="/contact">Contact</a></span></footer></body></html>`}
function toolPage(a){const options=a.options.map(o=>o.type==='select'?`<label>${esc(o.label)}<select data-opt="${o.id}">${o.values.map(v=>`<option value="${esc(v)}" ${v===o.default?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`:o.type==='checkbox'?`<label class="check"><input type="checkbox" data-opt="${o.id}" ${o.default?'checked':''}> ${esc(o.label)}</label>`:`<label>${esc(o.label)}<input data-opt="${o.id}" value="${esc(o.default||'')}"></label>`).join('');const faq=a.faq.map(x=>`<details><summary>${esc(x.q)}</summary><p>${esc(x.a)}</p></details>`).join('');const schema={"@context":"https://schema.org","@type":"WebApplication",name:a.name,applicationCategory:a.category,operatingSystem:"Any",description:a.description,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}};return layout(a.seoTitle,a.seoDescription,`<script type="application/ld+json">${JSON.stringify(schema)}</script><section class="tool-head"><p class="eyebrow">${esc(a.category)}</p><h1>${esc(a.h1)}</h1><p>${esc(a.description)}</p><div class="privacy-pill">Basic processing: in your browser</div></section><section class="tool-card" data-tool="${a.slug}" data-engine="${a.engine}"><div class="tool-grid"><div><label>${esc(a.inputLabel)}<textarea id="input" placeholder="${esc(a.placeholder)}">${esc(a.sample)}</textarea></label><label class="file-label">Load a local text/data file<input id="file-input" type="file" accept=".json,.csv,.tsv,.txt,.md,.html,.xml,.yaml,.yml,.log,text/*,application/json,text/csv"></label><div class="options">${options}</div><div class="actions"><button id="run">Process</button><button class="secondary" id="clear">Clear</button></div></div><div><label>${esc(a.outputLabel)}<textarea id="output" readonly></textarea></label><div class="actions"><button class="secondary" id="copy">Copy</button><button class="secondary" id="download">Download</button></div></div></div><p id="status" class="status"></p></section><section class="content"><h2>What this tool does</h2><p>${esc(a.explainer)}</p><h2>Automation/API</h2><pre>POST /api/tools/${a.slug}\nAuthorization: Bearer YOUR_API_KEY\n{"input":"...","options":{}}</pre><h2>FAQ</h2>${faq}</section>`,a.slug?`/${a.slug}`:'/')}
function home(){const groups=Object.groupBy(apps,a=>a.category);return layout('MicroForge — 50 fast, private microapps','A shared platform of fast browser tools with one API and credit system.',`<section class="hero"><p class="eyebrow">50 MICROAPPS · ONE ENGINE</p><h1>Small jobs. Instant results.</h1><p>Free browser-side utilities for everyday data, developer, SEO, business and construction tasks. One API and one shared credit balance for automation.</p><div class="actions"><a class="button" href="/tools">Browse 50 tools</a><a class="button secondary" href="/pricing">API & credits</a></div></section>${Object.entries(groups).map(([g,arr])=>`<section><h2>${esc(g)}</h2><div class="cards">${arr.slice(0,8).map(a=>`<a class="card" href="/${a.slug}"><strong>${esc(a.name)}</strong><span>${esc(a.description)}</span></a>`).join('')}</div></section>`).join('')}`)}
function tools(){return layout('All 50 Microapps | MicroForge','Browse all MicroForge utilities.',`<section><p class="eyebrow">CATALOG</p><h1>50 microapps</h1><input id="tool-search" class="search" placeholder="Search tools…"><div class="cards all-tools">${apps.map(a=>`<a class="card" data-search="${esc((a.name+' '+a.category+' '+a.description).toLowerCase())}" href="/${a.slug}"><strong>${esc(a.name)}</strong><small>${esc(a.category)}</small><span>${esc(a.description)}</span></a>`).join('')}</div></section>`,'/tools')}
function pricing(){return layout('Pricing | MicroForge','Shared credits for every MicroForge API tool.',`<section><p class="eyebrow">ONE BALANCE · ALL TOOLS</p><h1>Simple credits for automation</h1><p>Browser use stays free for normal limits. Credits are for API calls, batch workflows and future premium limits.</p><div class="pricing"><article><h2>Mini</h2><div class="price">$3</div><p>300 credits</p><button data-buy="mini">Buy Mini</button></article><article><h2>Basic</h2><div class="price">$7</div><p>1,000 credits</p><button data-buy="basic">Buy Basic</button></article><article><h2>Pro</h2><div class="price">$15</div><p>3,000 credits</p><button data-buy="pro">Buy Pro</button></article><article><h2>Monthly</h2><div class="price">$9/mo</div><p>2,000 credits / month</p><button data-buy="monthly">Subscribe</button></article></div><p id="payment-status" class="notice">Checking payment availability…</p><p class="notice">The payment provider handles card data. MicroForge only receives signed payment events and credits the shared account.</p></section><script src="https://cdn.paddle.com/paddle/v2/paddle.js"></script>`,'/pricing')}
const simple=(t,d,h,b,p)=>layout(t,d,`<section class="content"><h1>${h}</h1>${b}</section>`,p);
function sitemap(){return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['','tools','pricing','api-docs','privacy','terms','refunds','contact',...apps.map(a=>a.slug)].map(p=>`<url><loc>${BASE}/${p}</loc></url>`).join('')}</urlset>`}
function verifyPaddle(raw,sig,secret){if(!secret||!sig)return false;const parts=Object.fromEntries(sig.split(';').map(x=>x.split('=')));if(!parts.ts||!parts.h1)return false;const mac=crypto.createHmac('sha256',secret).update(`${parts.ts}:${raw}`).digest('hex');return crypto.timingSafeEqual(Buffer.from(mac),Buffer.from(parts.h1));}
function staticFile(req,res){const rel=req.url.replace('/assets/','');const p=path.join(publicDir,rel);if(!p.startsWith(publicDir)||!fs.existsSync(p))return false;const ext=path.extname(p);text(res,200,fs.readFileSync(p),ext==='.css'?'text/css; charset=utf-8':ext==='.js'?'text/javascript; charset=utf-8':'application/octet-stream');return true}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,BASE);try{
  if(req.method==='GET'&&url.pathname.startsWith('/assets/')){if(staticFile(req,res))return;text(res,404,'Not found');return}
  if(req.method==='GET'&&url.pathname==='/engines.js'){text(res,200,fs.readFileSync(path.resolve('src/engines.mjs')),'text/javascript; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/'){text(res,200,home(),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/tools'){text(res,200,tools(),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/pricing'){text(res,200,pricing(),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/privacy'){text(res,200,simple('Privacy | MicroForge','Privacy policy','Privacy policy','<p>Basic browser tools process input locally on your device. We do not intentionally store the content you paste into those tools. API requests are processed on the server to return the requested result; production deployments should use short-lived logs and avoid logging request bodies. We collect minimal operational analytics such as tool page, event type, anonymous session ID, referrer and country header when available.</p><p>Payment information is handled by the configured payment provider; MicroForge should not store card numbers.</p>','/privacy'),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/terms'){text(res,200,simple('Terms | MicroForge','Terms of service','Terms of service','<p>Tools are provided on an as-is basis. Users are responsible for verifying outputs before relying on them in production, legal, tax, safety or other high-stakes contexts. Abuse, illegal use and attempts to disrupt the service are prohibited.</p><p>Paid credits, refund rules and governing merchant terms should be finalized before live checkout is enabled.</p>','/terms'),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/refunds'){text(res,200,simple('Refund Policy | MicroForge','Refund policy for MicroForge credit packs and subscriptions','Refund Policy','<p>Last updated: October 7, 2026.</p><h2>One-time credit packs</h2><p>If you purchased a credit pack by mistake and the purchased credits have not been materially used, you may request a refund within 14 days of purchase. Once a substantial portion of credits has been consumed, the digital service has been delivered and the purchase may no longer be refundable except where required by applicable law.</p><h2>Subscriptions</h2><p>You may cancel a subscription at any time to prevent future renewal charges. Cancellation does not normally create a prorated refund for a billing period already started, except where required by applicable law or for duplicate or erroneous charges.</p><h2>Billing errors</h2><p>Duplicate charges, confirmed billing errors, and unauthorized transactions will be reviewed promptly. Approved refunds are returned through the original payment method and are subject to the payment provider processing time.</p><h2>Requesting a refund</h2><p>Use the MicroForge contact channel and include the transaction reference, purchase email, and a short description of the issue. Do not send card numbers or other sensitive payment credentials.</p><h2>Payment provider</h2><p>Payments and refunds may be processed by Paddle, our merchant-of-record/payment provider, under its buyer terms and statutory consumer protections.</p>','/refunds'),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/contact'){text(res,200,simple('Contact | MicroForge','Contact MicroForge','Contact','<p>Contact channel will be connected before public launch. For now this build intentionally avoids publishing a personal address.</p>','/contact'),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/api-docs'){text(res,200,simple('API Docs | MicroForge','Shared API documentation','API','<p>Create an API key with <code>POST /api/account</code>, then call any tool with <code>POST /api/tools/{slug}</code> and <code>Authorization: Bearer mf_…</code>. Each successful API call currently consumes one shared credit.</p><pre>curl -X POST /api/tools/json-formatter \\\n-H "Authorization: Bearer mf_YOUR_KEY" \\\n-H "Content-Type: application/json" \\\n-d \'{"input":"{\\"a\\":1}","options":{"indent":"2"}}\'</pre>','/api-docs'),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/sitemap.xml'){text(res,200,sitemap(),'application/xml; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/robots.txt'){text(res,200,`User-agent: *\nAllow: /\nSitemap: ${BASE}/sitemap.xml`);return}
  if(req.method==='GET'&&url.pathname==='/health'){json(res,200,{ok:true,apps:apps.length});return}
  if(req.method==='POST'&&url.pathname==='/api/events'){const b=JSON.parse((await body(req)).toString()||'{}');await logEvent({...b,ipCountry:req.headers['cf-ipcountry']||req.headers['x-vercel-ip-country']||null,referrer:req.headers.referer||null});json(res,202,{ok:true});return}
  if(req.method==='POST'&&url.pathname==='/api/account'){const b=JSON.parse((await body(req)).toString()||'{}');if(b.email&&!/^\S+@\S+\.\S+$/.test(b.email))return json(res,400,{error:'Invalid email'});json(res,201,await createUser(b.email||''));return}
  if(req.method==='GET'&&url.pathname==='/api/account'){const u=await getByApiKey((req.headers.authorization||'').replace(/^Bearer\s+/i,''));if(!u)return json(res,401,{error:'Invalid API key'});json(res,200,u);return}
  if(req.method==='POST'&&url.pathname.startsWith('/api/tools/')){const slug=url.pathname.split('/').pop(),a=bySlug[slug];if(!a)return json(res,404,{error:'Unknown tool'});const key=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const u=await getByApiKey(key);if(!u)return json(res,401,{error:'API key required'});const b=JSON.parse((await body(req)).toString()||'{}');const output=await runEngine(a.engine,b.input,b.options||{});const remaining=await useCredits(key,a.credits);await logEvent({type:'api_process',tool:slug,userId:u.id,credits:a.credits,estimatedCostUsd:0.00001});json(res,200,{output,creditsUsed:a.credits,creditsRemaining:remaining});return}
  if(req.method==='GET'&&url.pathname==='/api/payments/paddle/config'){json(res,200,{enabled:Boolean(process.env.PADDLE_CLIENT_TOKEN&&process.env.PADDLE_PRICE_MINI),environment:process.env.PADDLE_ENV||'sandbox',clientToken:process.env.PADDLE_CLIENT_TOKEN||null,prices:{mini:process.env.PADDLE_PRICE_MINI||null,basic:process.env.PADDLE_PRICE_BASIC||null,pro:process.env.PADDLE_PRICE_PRO||null,monthly:process.env.PADDLE_PRICE_MONTHLY||null}});return}
  if(req.method==='POST'&&url.pathname==='/api/payments/paddle/webhook'){const raw=(await body(req)).toString();if(process.env.PADDLE_WEBHOOK_FORWARD_URL){const rr=await fetch(process.env.PADDLE_WEBHOOK_FORWARD_URL,{method:'POST',headers:{'content-type':'application/json','paddle-signature':String(req.headers['paddle-signature']||'')},body:raw});const rt=await rr.text();res.writeHead(rr.status,{'content-type':rr.headers.get('content-type')||'application/json'});res.end(rt);return}if(!verifyPaddle(raw,req.headers['paddle-signature'],process.env.PADDLE_WEBHOOK_SECRET))return json(res,400,{error:'Invalid signature'});const ev=JSON.parse(raw);if(ev.event_type==='transaction.completed'){const d=ev.data||{},priceId=d.items?.[0]?.price?.id;const map={[process.env.PADDLE_PRICE_MINI]:300,[process.env.PADDLE_PRICE_BASIC]:1000,[process.env.PADDLE_PRICE_PRO]:3000,[process.env.PADDLE_PRICE_MONTHLY]:2000};const credits=map[priceId]||0;const userId=d.custom_data?.userId;const email=d.customer?.email||d.custom_data?.email||'';const result=credits&&userId?await grantCredits(userId,credits,d.id,email):null;await logEvent({type:'purchase',tool:d.custom_data?.tool||null,userId,revenue:Number(d.details?.totals?.grand_total||0)/100,currency:d.currency_code,paymentId:d.id,credits});json(res,200,{ok:true,result});return}json(res,200,{ok:true});return}
  if(req.method==='GET'&&url.pathname==='/admin'){if(url.searchParams.get('token')!==process.env.ADMIN_TOKEN)return text(res,401,'Unauthorized');const d=await getDashboard();const mini=(title,rows,metric)=>`<article class="rank"><h2>${title}</h2><ol>${rows.slice(0,5).map(x=>`<li><span>${esc(x.tool)}</span><b>${metric(x)}</b></li>`).join('')}</ol></article>`;text(res,200,layout('Admin | MicroForge','Admin dashboard',`<section><h1>MicroForge dashboard</h1><div class="stats"><div><b>${d.users}</b><span>users</span></div><div><b>${d.events}</b><span>events</span></div><div><b>$${d.revenue.toFixed(2)}</b><span>revenue</span></div><div><b>$${d.estimatedCostUsd.toFixed(4)}</b><span>est. compute cost</span></div></div><div class="rankings">${mini('Top traffic',d.rankings.traffic,x=>x.visits)}${mini('Top conversion',d.rankings.conversion,x=>x.conversionRate+'%')}${mini('Top revenue',d.rankings.revenue,x=>'$'+x.revenue.toFixed(2))}${mini('Top growth',d.rankings.growth,x=>x.growthPercent+'%')}</div><table><thead><tr><th>Tool</th><th>Views</th><th>Runs</th><th>API</th><th>Sales</th><th>Revenue</th><th>Conv.</th><th>Growth</th></tr></thead><tbody>${d.tools.map(x=>`<tr><td>${esc(x.tool)}</td><td>${x.visits}</td><td>${x.processes}</td><td>${x.api}</td><td>${x.conversions}</td><td>$${x.revenue.toFixed(2)}</td><td>${x.conversionRate}%</td><td>${x.growthPercent}%</td></tr>`).join('')}</tbody></table></section>`,'/admin'),'text/html; charset=utf-8');return}
  if(req.method==='GET'){const slug=url.pathname.slice(1);const a=bySlug[slug];if(a){text(res,200,toolPage(a),'text/html; charset=utf-8');return}}
  text(res,404,'Not found');
}catch(e){await logEvent({type:'error',path:url.pathname,message:e.message});json(res,e.status||400,{error:e.message})}});
server.listen(PORT,()=>{console.log(`MicroForge listening on ${BASE}`);if(process.env.PADDLE_CLIENT_TOKEN){fetch('https://api.paddle.com/checkout-domains',{headers:{authorization:`Bearer ${process.env.PADDLE_CLIENT_TOKEN}`}}).then(async r=>{const t=await r.text();console.log('PADDLE_DOMAIN_DIAG',r.status,t.slice(0,1200));}).catch(e=>console.log('PADDLE_DOMAIN_DIAG_ERROR',e.message));}});
