import {executeTool} from './execution.mjs';
import {toolDefinitions,openapi} from './discovery.mjs';
import {verifyPaddle,validateInput,allowRequest,hashKey} from './security.mjs';
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {apps,bySlug} from './catalog.mjs';import {runEngine} from './engines.mjs';import {createUser,getByApiKey,useCredits,grantCredits,logEvent,getDashboard,storageMode,paymentsReady} from './store.mjs';
const PORT=Number(process.env.PORT||8787);const BASE=process.env.BASE_URL||`http://localhost:${PORT}`;
const publicDir=path.resolve('public');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=(res,status,obj)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(obj))};
const text=(res,status,body,type='text/plain; charset=utf-8')=>{res.writeHead(status,{'content-type':type});res.end(body)};
const body=async(req,max=1_000_000)=>{let chunks=[],size=0;for await(const c of req){size+=c.length;if(size>max)throw Object.assign(new Error('Payload too large'),{status:413});chunks.push(c)}return Buffer.concat(chunks)};
function layout(title,desc,content,canonical='/'){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${BASE}${canonical}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:type" content="website"><meta property="og:url" content="${BASE}${canonical}"><link rel="stylesheet" href="/assets/styles.css"><script type="module" src="/assets/client.js"></script></head><body><header><a class="brand" href="/">MicroForge</a><nav><a href="/tools">Tools</a><a href="/pricing">Pricing</a><a href="/api-docs">API</a><a href="/privacy">Privacy</a></nav></header><main>${content}</main><footer><span>MicroForge — small tools, one shared platform.</span><span><a href="/terms">Terms</a> · <a href="/refunds">Refunds</a> · <a href="/contact">Contact</a></span></footer></body></html>`}
function toolPage(a){const options=a.options.map(o=>o.type==='select'?`<label>${esc(o.label)}<select data-opt="${o.id}">${o.values.map(v=>`<option value="${esc(v)}" ${v===o.default?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`:o.type==='checkbox'?`<label class="check"><input type="checkbox" data-opt="${o.id}" ${o.default?'checked':''}> ${esc(o.label)}</label>`:`<label>${esc(o.label)}<input data-opt="${o.id}" value="${esc(o.default||'')}"></label>`).join('');const faq=a.faq.map(x=>`<details><summary>${esc(x.q)}</summary><p>${esc(x.a)}</p></details>`).join('');const schema={"@context":"https://schema.org","@type":"WebApplication",name:a.name,applicationCategory:a.category,operatingSystem:"Any",description:a.description,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}};return layout(a.seoTitle,a.seoDescription,`<script type="application/ld+json">${JSON.stringify(schema)}</script><section class="tool-head"><p class="eyebrow">${esc(a.category)}</p><h1>${esc(a.h1)}</h1><p>${esc(a.description)}</p><div class="privacy-pill">Basic processing: in your browser</div></section><section class="tool-card" data-tool="${a.slug}" data-engine="${a.engine}"><div class="tool-grid"><div><label>${esc(a.inputLabel)}<textarea id="input" placeholder="${esc(a.placeholder)}">${esc(a.sample)}</textarea></label><label class="file-label">Load a local text/data file<input id="file-input" type="file" accept=".json,.csv,.tsv,.txt,.md,.html,.xml,.yaml,.yml,.log,text/*,application/json,text/csv"></label><div class="options">${options}</div><div class="actions"><button id="run">Process</button><button class="secondary" id="clear">Clear</button></div></div><div><label>${esc(a.outputLabel)}<textarea id="output" readonly></textarea></label><div class="actions"><button class="secondary" id="copy">Copy</button><button class="secondary" id="download">Download</button></div></div></div><p id="status" class="status"></p></section><section class="content"><h2>What this tool does</h2><p>${esc(a.explainer)}</p><h2>Automation/API</h2><pre>POST /api/tools/${a.slug}\nAuthorization: Bearer YOUR_API_KEY\n{"input":"...","options":{}}</pre><h2>FAQ</h2>${faq}</section>`,a.slug?`/tools/${a.slug}`:'/')}
function home(){const groups=Object.groupBy(apps,a=>a.category);return layout('MicroForge — 50 fast, private microapps','A shared platform of fast browser tools with one API and credit system.',`<section class="hero"><p class="eyebrow">50 MICROAPPS · ONE ENGINE</p><h1>Small jobs. Instant results.</h1><p>Free browser-side utilities for everyday data, developer, SEO, business and construction tasks. One API and one shared credit balance for automation.</p><div class="actions"><a class="button" href="/tools">Browse 50 tools</a><a class="button secondary" href="/pricing">API & credits</a></div></section>${Object.entries(groups).map(([g,arr])=>`<section><h2>${esc(g)}</h2><div class="cards">${arr.slice(0,8).map(a=>`<a class="card" href="/tools/${a.slug}"><strong>${esc(a.name)}</strong><span>${esc(a.description)}</span></a>`).join('')}</div></section>`).join('')}`)}
function tools(){return layout('All 50 Microapps | MicroForge','Browse all MicroForge utilities.',`<section><p class="eyebrow">CATALOG</p><h1>50 microapps</h1><input id="tool-search" class="search" placeholder="Search tools…"><div class="cards all-tools">${apps.map(a=>`<a class="card" data-search="${esc((a.name+' '+a.category+' '+a.description).toLowerCase())}" href="/tools/${a.slug}"><strong>${esc(a.name)}</strong><small>${esc(a.category)}</small><span>${esc(a.description)}</span></a>`).join('')}</div></section>`,'/tools')}
function pricing(){return layout('Pricing | MicroForge','Shared credits for every MicroForge API tool.',`<section><p class="eyebrow">ONE BALANCE · ALL TOOLS</p><h1>Simple credits for automation</h1><p>Browser use stays free for normal limits. Credits are for API calls, batch workflows and future premium limits.</p><div class="pricing"><article><h2>Mini</h2><div class="price">$3</div><p>300 credits</p><button data-buy="mini">Buy Mini</button></article><article><h2>Basic</h2><div class="price">$7</div><p>1,000 credits</p><button data-buy="basic">Buy Basic</button></article><article><h2>Pro</h2><div class="price">$15</div><p>3,000 credits</p><button data-buy="pro">Buy Pro</button></article><article><h2>Monthly</h2><div class="price">$9/mo</div><p>2,000 credits / month</p><button data-buy="monthly">Subscribe</button></article></div><p id="payment-status" class="notice">Checking payment availability…</p><p class="notice">The payment provider handles card data. MicroForge only receives signed payment events and credits the shared account.</p></section><script src="https://cdn.paddle.com/paddle/v2/paddle.js"></script>`,'/pricing')}
const simple=(t,d,h,b,p)=>layout(t,d,`<section class="content"><h1>${h}</h1>${b}</section>`,p);
function apiDocs(){const payload=JSON.stringify({input:'{"a":1}',options:{indent:'2'}});return simple('API Docs | MicroForge','Shared API documentation','API',`<p><a href="/openapi.json">OpenAPI specification</a> · <a href="/api/tools">Catalog with input schemas, options and credits_cost</a></p><p>Create an account with POST /api/account. Its API key is shown once; store it securely. A successful POST /api/tools/{slug} consumes the tool cost from your balance. Invalid requests are not charged.</p><h2>Request and response</h2><pre>${esc(payload)}</pre><pre>${esc(JSON.stringify({output:'{\n  "a": 1\n}',creditsUsed:1,credits_cost:1,creditsRemaining:299,latencyMs:1},null,2))}</pre><h2>curl</h2><pre>${esc(`curl -X POST "${BASE}/api/tools/json-formatter" -H "Authorization: Bearer YOUR_API_KEY" -H "Content-Type: application/json" --data '${payload}'`)}</pre><h2>JavaScript</h2><pre>${esc(`const response = await fetch("${BASE}/api/tools/json-formatter", {
  method: "POST",
  headers: {Authorization: "Bearer " + apiKey, "Content-Type": "application/json"},
  body: JSON.stringify({input: JSON.stringify({a: 1}), options: {indent: "2"}})
});
const result = await response.json();
if (!response.ok) throw new Error(result.error);
console.log(result.output);`)}</pre><h2>Python</h2><pre>${esc(`import json, urllib.request
request = urllib.request.Request("${BASE}/api/tools/json-formatter",
    data=json.dumps({"input": json.dumps({"a": 1}), "options": {"indent": "2"}}).encode(),
    headers={"Authorization": "Bearer " + api_key, "Content-Type": "application/json"},
    method="POST")
with urllib.request.urlopen(request) as response:
    print(json.load(response)["output"])`)}</pre><h2>Errors</h2><p>400 invalid JSON/input/options, 401 invalid API key, 402 insufficient credits, 404 unknown slug, 413 input too large, 429 rate limited, 500/503 service or persistent storage unavailable. Billing remains disabled until persistent storage has been verified. Never include API keys in URLs or public client code.</p>`,'/api-docs')}
function sitemap(){return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['','tools','pricing','api-docs','privacy','terms','refunds','contact',...apps.map(a=>'tools/'+a.slug)].map(p=>`<url><loc>${BASE}/${p}</loc></url>`).join('')}</urlset>`}
function staticFile(req,res){const rel=new URL(req.url,BASE).pathname.replace('/assets/','');const p=path.resolve(publicDir,rel);if(!p.startsWith(publicDir+path.sep)||!fs.existsSync(p))return false;const ext=path.extname(p);text(res,200,fs.readFileSync(p),ext==='.css'?'text/css; charset=utf-8':ext==='.js'?'text/javascript; charset=utf-8':'application/octet-stream');return true}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,BASE);try{
  res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');
  if(url.pathname.startsWith('/api/')){res.setHeader('Access-Control-Allow-Origin','*');if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'authorization,content-type','access-control-max-age':'600'});res.end();return}}
  if(url.pathname.startsWith('/api/') && !url.pathname.endsWith('/webhook')){
    const ip=String(req.headers['cf-connecting-ip']||req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim();
    if(!allowRequest('ip:'+ip,url.pathname==='/api/contact'?5:url.pathname==='/api/account'?20:300))return json(res,429,{error:'Rate limit exceeded'});
    const auth=req.headers.authorization;if(auth&&!allowRequest('key:'+hashKey(auth),120))return json(res,429,{error:'API key rate limit exceeded'});
  }
  if(req.method==='GET'&&url.pathname.startsWith('/assets/')){if(staticFile(req,res))return;text(res,404,'Not found');return}
  if(req.method==='GET'&&url.pathname==='/engines.js'){text(res,200,fs.readFileSync(path.resolve('src/engines.mjs')),'text/javascript; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/'){text(res,200,home(),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/tools'){text(res,200,tools(),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/pricing'){text(res,200,pricing(),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/privacy'){text(res,200,simple('Privacy | MicroForge','Privacy policy','Privacy policy','<p>Basic browser tools process input locally on your device. We do not intentionally store the content you paste into those tools. API requests are processed on the server to return the requested result; production deployments should use short-lived logs and avoid logging request bodies. We collect minimal operational analytics such as tool page, event type, anonymous session ID, referrer and country header when available.</p><p>Payment information is handled by the configured payment provider; MicroForge should not store card numbers.</p>','/privacy'),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/terms'){text(res,200,simple('Terms | MicroForge','Terms of service','Terms of service','<p>Tools are provided on an as-is basis. Users are responsible for verifying outputs before relying on them in production, legal, tax, safety or other high-stakes contexts. Abuse, illegal use and attempts to disrupt the service are prohibited.</p><p>Paid credits and subscriptions are governed by the prices shown at checkout and the MicroForge Refund Policy. Paddle processes eligible payments as merchant of record. Credits have no cash value and may not be transferred between accounts unless required by law.</p>','/terms'),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/refunds'){text(res,200,simple('Refund Policy | MicroForge','Refund policy for MicroForge credit packs and subscriptions','Refund Policy','<p>Last updated: October 7, 2026.</p><h2>One-time credit packs</h2><p>If you purchased a credit pack by mistake and the purchased credits have not been materially used, you may request a refund within 14 days of purchase. Once a substantial portion of credits has been consumed, the digital service has been delivered and the purchase may no longer be refundable except where required by applicable law.</p><h2>Subscriptions</h2><p>You may cancel a subscription at any time to prevent future renewal charges. Cancellation does not normally create a prorated refund for a billing period already started, except where required by applicable law or for duplicate or erroneous charges.</p><h2>Billing errors</h2><p>Duplicate charges, confirmed billing errors, and unauthorized transactions will be reviewed promptly. Approved refunds are returned through the original payment method and are subject to the payment provider processing time.</p><h2>Requesting a refund</h2><p>Use the MicroForge contact channel and include the transaction reference, purchase email, and a short description of the issue. Do not send card numbers or other sensitive payment credentials.</p><h2>Payment provider</h2><p>Payments and refunds may be processed by Paddle, our merchant-of-record/payment provider, under its buyer terms and statutory consumer protections.</p>','/refunds'),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/contact'){text(res,200,simple('Contact | MicroForge','Contact MicroForge','Contact','<p>Send a billing, refund or technical support request. Include your transaction reference when relevant; do not send passwords or card details.</p><form id="contact-form"><label>Email <input name="email" type="email" required maxlength="254"></label><label>Message <textarea name="message" required minlength="5" maxlength="4000"></textarea></label><button type="submit">Send request</button><p id="contact-status" role="status"></p></form><script>document.getElementById("contact-form").addEventListener("submit",async e=>{e.preventDefault();const form=e.target,status=document.getElementById("contact-status"),button=form.querySelector("button");button.disabled=true;try{const r=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:form.email.value,message:form.message.value})});if(!r.ok)throw new Error("Request could not be saved. Please retry later.");status.textContent="Request saved.";form.reset()}catch(e){status.textContent=e.message}finally{button.disabled=false}});</script>','/contact'),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/api-docs'){text(res,200,apiDocs(),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/sitemap.xml'){text(res,200,sitemap(),'application/xml; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname==='/robots.txt'){text(res,200,`User-agent: *\nAllow: /\nSitemap: ${BASE}/sitemap.xml`);return}
  if(req.method==='GET'&&url.pathname==='/api/tools'){json(res,200,{tools:toolDefinitions()});return}
  if(req.method==='GET'&&url.pathname==='/openapi.json'){json(res,200,openapi(BASE));return}
  if(req.method==='GET'&&url.pathname==='/llms.txt'){text(res,200,`# MicroForge\n\nBrowser utilities and authenticated credit API.\n\n- [API documentation](${BASE}/api-docs)\n- [OpenAPI](${BASE}/openapi.json)\n- [Tool catalog](${BASE}/api/tools)\n\nPOST /api/tools/{slug} with a Bearer API key and JSON input/options. Read credits_cost from the catalog. Paid access is unavailable until billing storage is verified.\n`);return}
  if(req.method==='GET'&&url.pathname==='/health'){json(res,200,{ok:true,apps:apps.length,storage:storageMode,persistence:storageMode==='local'?'local-ephemeral':storageMode,paymentsReady:paymentsReady(),diagnostics:{supabaseUrlPresent:Boolean(process.env.SUPABASE_URL),supabaseServiceRolePresent:Boolean(process.env.SUPABASE_SERVICE_ROLE_KEY),persistenceVerified:process.env.PERSISTENCE_VERIFIED==='true',paddleWebhookSecretPresent:Boolean(process.env.PADDLE_WEBHOOK_SECRET)}});return}
  if(req.method==='POST'&&url.pathname==='/api/events'){const b=JSON.parse((await body(req,65536)).toString()||'{}');if(!['view','process','checkout_started','checkout_completed','browser_error'].includes(b.type))return json(res,400,{error:'Invalid event type'});await logEvent({type:b.type,tool:bySlug[b.tool]?b.tool:null,ipCountry:req.headers['cf-ipcountry']||req.headers['x-vercel-ip-country']||null,referrer:req.headers.referer||null});json(res,202,{ok:true});return}
  if(req.method==='POST'&&url.pathname==='/api/contact'){const b=JSON.parse((await body(req,16384)).toString()||'{}');if(typeof b.email!=='string'||typeof b.message!=='string')return json(res,400,{error:'Valid email and message required'});const email=b.email.trim(),message=b.message.trim();if(email.length>254||!/^\S+@\S+\.\S+$/.test(email)||message.length<5||message.length>4000)return json(res,400,{error:'Valid email and message required'});await logEvent({type:'contact',email,message});json(res,202,{ok:true});return}
  if(req.method==='POST'&&url.pathname==='/api/account'){const b=JSON.parse((await body(req,8192)).toString()||'{}');if(b.email&&!/^\S+@\S+\.\S+$/.test(b.email))return json(res,400,{error:'Invalid email'});json(res,201,await createUser(b.email||''));return}
  if(req.method==='GET'&&url.pathname==='/api/account'){const u=await getByApiKey((req.headers.authorization||'').replace(/^Bearer\s+/i,''));if(!u)return json(res,401,{error:'Invalid API key'});const {apiKey,...account}=u;json(res,200,account);return}
  if(req.method==='POST'&&url.pathname.startsWith('/api/tools/')){const slug=url.pathname.split('/').pop(),a=bySlug[slug];if(!a)return json(res,404,{error:'Unknown tool'});const key=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const u=await getByApiKey(key);if(!u)return json(res,401,{error:'API key required'});const b=JSON.parse((await body(req)).toString()||'{}');validateInput(b);if(Number(u.credits||0)<a.credits)return json(res,402,{error:'Insufficient credits'});if(b.input.length>a.freeLimit)return json(res,413,{error:'Input too large'});const started=performance.now();let output;try{output=await executeTool(a.engine,b.input,b.options||{});}catch(e){throw Object.assign(new Error(e.message),{status:e.status||400});}const latencyMs=Number((performance.now()-started).toFixed(3));const remaining=await useCredits(key,a.credits,{tool:slug,requestId:crypto.randomUUID(),latencyMs});if(storageMode!=='supabase')try{await logEvent({type:'api_process',tool:slug,userId:u.id,credits:a.credits,latencyMs});}catch{}json(res,200,{output,creditsUsed:a.credits,creditsRemaining:remaining,credits_cost:a.credits,latencyMs});return}
  if(req.method==='GET'&&url.pathname==='/api/payments/paddle/config'){json(res,200,{enabled:Boolean(paymentsReady()&&process.env.PADDLE_CLIENT_TOKEN&&process.env.PADDLE_PRICE_MINI),environment:process.env.PADDLE_ENV||'sandbox',clientToken:process.env.PADDLE_CLIENT_TOKEN||null,prices:{mini:process.env.PADDLE_PRICE_MINI||null,basic:process.env.PADDLE_PRICE_BASIC||null,pro:process.env.PADDLE_PRICE_PRO||null,monthly:process.env.PADDLE_PRICE_MONTHLY||null}});return}
  if(req.method==='POST'&&url.pathname==='/api/payments/paddle/webhook'){const raw=(await body(req)).toString();if(process.env.PADDLE_WEBHOOK_FORWARD_URL){const rr=await fetch(process.env.PADDLE_WEBHOOK_FORWARD_URL,{method:'POST',headers:{'content-type':'application/json','paddle-signature':String(req.headers['paddle-signature']||'')},body:raw});const rt=await rr.text();res.writeHead(rr.status,{'content-type':rr.headers.get('content-type')||'application/json'});res.end(rt);return}if(!verifyPaddle(raw,req.headers['paddle-signature'],process.env.PADDLE_WEBHOOK_SECRET))return json(res,400,{error:'Invalid signature'});if(!paymentsReady())return json(res,503,{error:'Persistent billing storage not verified'});const ev=JSON.parse(raw);if(ev.event_type==='transaction.completed'){const d=ev.data||{};const map=Object.fromEntries([[process.env.PADDLE_PRICE_MINI,300],[process.env.PADDLE_PRICE_BASIC,1000],[process.env.PADDLE_PRICE_PRO,3000],[process.env.PADDLE_PRICE_MONTHLY,2000]].filter(([id])=>id));let credits=0;if(!Array.isArray(d.items)||!d.items.length)return json(res,422,{error:'Missing purchase items'});for(const item of d.items){const n=item.quantity??1;if(!map[item.price?.id]||!Number.isSafeInteger(n)||n<1||n>100)return json(res,422,{error:'Unrecognized price or quantity'});credits+=map[item.price.id]*n;}const userId=d.custom_data?.userId;const email=d.customer?.email||d.custom_data?.email||'';if(!credits||!userId||!d.id||!ev.event_id)return json(res,422,{error:'Unrecognized price or missing payment account'});const result=await grantCredits(userId,credits,d.id,email,{eventId:ev.event_id,subscriptionId:d.subscription_id,currency:d.currency_code,revenue:Number(d.details?.totals?.grand_total||0)/100,tool:d.custom_data?.tool});if(!result.duplicate&&storageMode!=='supabase')await logEvent({type:'purchase',tool:d.custom_data?.tool||null,userId,revenue:Number(d.details?.totals?.grand_total||0)/100,currency:d.currency_code,paymentId:d.id,credits});json(res,200,{ok:true,result});return}json(res,200,{ok:true});return}
  if(req.method==='GET'&&url.pathname==='/admin'){if(!process.env.ADMIN_TOKEN||url.searchParams.get('token')!==process.env.ADMIN_TOKEN)return text(res,401,'Unauthorized');const d=await getDashboard();const contacts=(d.contacts||[]).map(x=>`<li><b>${esc(x.email)}</b> — ${esc(x.message).slice(0,300)} <small>${esc(x.ts)}</small></li>`).join('');const mini=(title,rows,metric)=>`<article class="rank"><h2>${title}</h2><ol>${rows.slice(0,5).map(x=>`<li><span>${esc(x.tool)}</span><b>${metric(x)}</b></li>`).join('')}</ol></article>`;text(res,200,layout('Admin | MicroForge','Admin dashboard',`<section><h1>MicroForge dashboard</h1><div class="stats"><div><b>${d.users}</b><span>users</span></div><div><b>${d.events}</b><span>events</span></div><div><b>$${d.revenue.toFixed(2)}</b><span>revenue</span></div><div><b>$${d.estimatedCostUsd.toFixed(4)}</b><span>est. compute cost</span></div></div><div class="rankings">${mini('Top traffic',d.rankings.traffic,x=>x.visits)}${mini('Top conversion',d.rankings.conversion,x=>x.conversionRate+'%')}${mini('Top revenue',d.rankings.revenue,x=>'$'+x.revenue.toFixed(2))}${mini('Top growth',d.rankings.growth,x=>x.growthPercent+'%')}</div><h2>Recent contact requests</h2><ul>${contacts||'<li>None</li>'}</ul><table><thead><tr><th>Tool</th><th>Views</th><th>Runs</th><th>API</th><th>Sales</th><th>Revenue</th><th>Conv.</th><th>Growth</th></tr></thead><tbody>${d.tools.map(x=>`<tr><td>${esc(x.tool)}</td><td>${x.visits}</td><td>${x.processes}</td><td>${x.api}</td><td>${x.conversions}</td><td>$${x.revenue.toFixed(2)}</td><td>${x.conversionRate}%</td><td>${x.growthPercent}%</td></tr>`).join('')}</tbody></table></section>`,'/admin'),'text/html; charset=utf-8');return}
  if(req.method==='GET'&&url.pathname.startsWith('/tools/')){const slug=url.pathname.slice('/tools/'.length),a=bySlug[slug];if(a){text(res,200,toolPage(a),'text/html; charset=utf-8');return}}
  if(req.method==='GET'){const slug=url.pathname.slice(1);if(bySlug[slug]){res.writeHead(301,{location:`/tools/${slug}`});res.end();return}}
  text(res,404,'Not found');
}catch(e){try{await logEvent({type:'error',path:url.pathname});}catch{}json(res,e instanceof SyntaxError?400:e.status||500,{error:e instanceof SyntaxError?'Invalid JSON':e.status?e.message:'Request could not be completed'})}});
server.listen(PORT,()=>console.log(`MicroForge listening on ${BASE} port ${server.address().port}`));
// Startup persistence probe: no credentials or user data are printed.
console.log('MF_PERSISTENCE_PROBE_CONFIG',JSON.stringify({storageMode,hasUrl:Boolean(process.env.SUPABASE_URL),hasServiceRole:Boolean(process.env.SUPABASE_SERVICE_ROLE_KEY)}));
if (storageMode === 'supabase' && process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY) {
  (async () => {
    try {
      const account = await createUser('');
      const loaded = await getByApiKey(account.apiKey);
      if (!loaded || loaded.id !== account.id) throw new Error('Readback mismatch');
      console.log('MF_PERSISTENCE_SMOKE_PASS');
    } catch (error) {
      console.error('MF_PERSISTENCE_SMOKE_FAIL', error.status || 'unknown');
    }
  })();
}

